// DO NOT EDIT MANUALLY
// This file was automatically generated by `processing/steps/generateTypes.ts`
// To update, run `docker compose up processing`

const tableNames = [
  'barrierAreas',
  'barrierLines',
  'bicycleParking_areas',
  'bicycleParking_points',
  'bikeSuitability',
  'bikelanes',
  'bikelanesPresence',
  'bikeroutes',
  'boundaries',
  'boundaryLabels',
  'landuse',
  'off_street_parking_area_labels',
  'off_street_parking_areas',
  'off_street_parking_points',
  'parking_errors',
  'places',
  'poiClassification',
  'publicTransport',
  'roads',
  'roadsPathClasses',
  'trafficSigns',
]
export type TableNames = (typeof tableNames)[number]
