// DO NOT EDIT MANUALLY
// This file was automatically generated by `processing/steps/generateTypes.ts`
// To update, run `docker compose up processing` with ENV=development

export type TableId =
  | 'barrierAreas'
  | 'barrierLines'
  | 'bicycleParking_areas'
  | 'bicycleParking_points'
  | 'bikeSuitability'
  | 'bikelanes'
  | 'bikelanesPresence'
  | 'bikeroutes'
  | 'boundaries'
  | 'boundaryLabels'
  | 'landuse'
  | 'off_street_parking_area_labels'
  | 'off_street_parking_areas'
  | 'off_street_parking_points'
  | 'parkings'
  | 'parkings_no'
  | 'parkings_separate'
  | 'places'
  | 'poiClassification'
  | 'publicTransport'
  | 'roads'
  | 'roadsPathClasses'
  | 'trafficSigns'
