// DO NOT EDIT MANUALLY
// This file was automatically generated by `processing/steps/generateTypes.ts`
// To update, run `docker compose up processing`

export const bikelaneTodoKeysTableAndField = [
  'adjoining_or_isolated',
  'advisory_or_exclusive',
  'missing_access_tag_240',
  'missing_access_tag_bicycle_road',
  'missing_oneway',
  'missing_segregated',
  'mixed_cycleway_both',
  'needs_clarification',
  'needs_clarification_track',
  'unexpected_bicycle_access_on_footway',
] as const
export type BikelaneTodoKeysTableAndField = (typeof bikelaneTodoKeysTableAndField)[number]

export const bikelaneTodoKeysTableOnly = [
  'currentness_too_old',
  'malformed_traffic_sign',
  'missing_surface',
  'missing_traffic_sign',
  'missing_traffic_sign_244',
  'missing_traffic_sign_vehicle_destination',
  'missing_width',
  'missing_width_surface_sett',
] as const
export type BikelaneTodoKeysTableOnly = (typeof bikelaneTodoKeysTableOnly)[number]

export const roadTodoKeysTableAndField = ['deprecated_cycleway_shared'] as const
export type RoadTodoKeysTableAndField = (typeof roadTodoKeysTableAndField)[number]

export const roadTodoKeysTableOnly = [] as const
export type RoadTodoKeysTableOnly = (typeof roadTodoKeysTableOnly)[number]
