// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_maxspeed_presence: MapboxStyleLayer[] = [
  {
    id: 'maxspeed_presence',
    type: 'line',
    filter: [
      'match',
      ['get', 'road'],
      ['footway', 'path', 'cycleway', 'footway_steps', 'track', 'bridleway', 'pedestrian'],
      false,
      true,
    ],
    paint: {
      'line-color': ['case', ['has', 'maxspeed'], '#8eb1f0', '#fa80f4'],
      'line-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11,
        ['case', ['has', 'maxspeed'], 0, 0.7],
        12,
        ['case', ['has', 'maxspeed'], 0.7, 0.5],
      ],
      'line-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        8,
        1,
        16,
        ['case', ['has', 'maxspeed'], 4, 6],
      ],
    },
  },
  {
    id: 'hitarea-maxspeed-presence',
    type: 'line',
    filter: [
      'match',
      ['get', 'road'],
      ['footway', 'footway_crossing', 'path', 'cycleway', 'bridleway', 'track', 'pedestrian'],
      false,
      true,
    ],
    layout: {
      'line-cap': 'round',
    },
    paint: {
      'line-color': 'rgb(216, 20, 255)',
      'line-opacity': 0,
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
    },
  },
]
