// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_maxspeed_below30: MapboxStyleLayer[] = [
  {
    id: 'maxspeed-kleinergleich30',
    type: 'line',
    filter: ['<=', ['get', 'maxspeed'], 30],
    layout: {
      'line-cap': 'round',
    },
    paint: {
      'line-color': [
        'interpolate',
        ['linear'],
        ['get', 'maxspeed'],
        20,
        '#08aec4',
        30,
        '#2cb587',
        80,
        '#b80505',
      ],
      'line-opacity': 0.98,
      'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 15, 1],
    },
  },
  {
    id: 'hitarea-maxspeed30',
    type: 'line',
    filter: ['<=', ['get', 'maxspeed'], 30],
    layout: {
      'line-cap': 'round',
    },
    paint: {
      'line-color': 'rgb(216, 20, 255)',
      'line-opacity': 0,
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1, 14.1, 10, 22, 12],
    },
  },
]
