// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_bikelanes_unspecified: MapboxStyleLayer[] = [
  {
    id: 'unspecified',
    type: 'line',
    filter: [
      'match',
      ['get', 'category'],
      [
        'cycleway_adjoiningOrIsolated',
        'footAndCyclewayShared_adjoiningOrIsolated',
        'cyclewayOnHighway_advisoryOrExclusive',
        'footwayBicycleYes_adjoiningOrIsolated',
        'footAndCyclewaySegregated_adjoiningOrIsolated',
        'needsClarification',
      ],
      true,
      false,
    ],
    minzoom: 7,
    paint: {
      'line-color': '#b50382',
      'line-opacity': 0.3,
      'line-width': ['interpolate', ['linear'], ['zoom'], 9, 5, 13, 8, 18, 20],
    },
  },
]
