// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_lit_complete: MapboxStyleLayer[] = [
  {
    id: 'lit-missing',
    type: 'line',
    filter: ['!', ['has', 'lit']],
    paint: {
      'line-color': '#fa80f4',
      'line-opacity': 0.7,
      'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 14, 1.5, 18, 3],
    },
  },
]
