// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_parking_debug_parking_poly: MapboxStyleLayer[] = [
  {
    id: 'parking-poly-area',
    type: 'fill',
    minzoom: 15,
    paint: {
      'fill-color': 'hsla(208, 47%, 38%, 0.7)',
    },
  },
  {
    id: 'parking-poly-border',
    type: 'line',
    minzoom: 16.5,
    paint: {
      'line-color': 'rgb(0, 0, 0)',
      'line-dasharray': [2, 2],
    },
  },
]
