// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_off_surface_area: MapboxStyleLayer[] = [
  {
    id: 'off_surface_bg',
    type: 'line',
    paint: {
      'line-color': ['match', ['get', 'surface'], ['compacted'], 'rgb(239, 108, 108)', 'red'],
      'line-dasharray': [
        'case',
        ['==', ['get', 'parking'], 'underground'],
        ['literal', [3, 2]],
        ['literal', []],
      ],
      'line-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        15,
        ['match', ['get', 'parking'], ['surface'], 0, 0.5],
        19,
        ['match', ['get', 'parking'], ['surface'], 0, 4],
      ],
    },
  },
  {
    id: 'off_surface_outline',
    type: 'fill',
    paint: {
      'fill-color': ['match', ['get', 'surface'], ['compacted'], 'rgb(239, 108, 108)', 'red'],
    },
  },
]
