// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_parking_obstacles: MapboxStyleLayer[] = [
  {
    id: 'area',
    type: 'fill',
    minzoom: 15,
    paint: {
      'fill-color': 'rgb(219, 39, 119)',
    },
  },
  {
    id: 'border',
    type: 'line',
    minzoom: 16.5,
    paint: {
      'line-color': 'rgb(0, 0, 0)',
      'line-dasharray': [2, 2],
    },
  },
]
