// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_off_default_area: MapboxStyleLayer[] = [
  {
    id: 'off_type_bg',
    type: 'fill',
    paint: {
      'fill-color': [
        'case',
        ['match', ['get', 'parking'], ['multi-storey'], true, false],
        'rgb(233, 91, 84)',
        ['match', ['get', 'parking'], ['underground'], true, false],
        'rgb(142, 192, 169)',
        ['match', ['get', 'parking'], ['carports', 'carport'], true, false],
        'rgb(251, 206, 74)',
        ['match', ['get', 'building'], ['garages', 'garage', 'carport'], true, false],
        'rgb(251, 206, 74)',
        'rgb(48, 159, 219)',
      ],
    },
  },
  {
    id: 'off_type_outline',
    type: 'line',
    paint: {
      'line-dasharray': [
        'case',
        ['==', ['get', 'parking'], 'underground'],
        ['literal', [3, 2]],
        ['literal', []],
      ],
      'line-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        15,
        ['match', ['get', 'parking'], ['surface'], 0, 0.5],
        19,
        ['match', ['get', 'parking'], ['surface'], 0, 4],
      ],
    },
  },
]
