// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_off_labels: MapboxStyleLayer[] = [
  {
    id: 'areas-labels',
    type: 'symbol',
    layout: {
      'text-field': ['to-string', ['get', 'capacity']],
      'text-size': ['interpolate', ['linear'], ['zoom'], 14.99, 0, 15, 9, 20, 20],
    },
    paint: {
      'text-color': 'rgb(255, 255, 255)',
      'text-halo-color': 'rgba(0, 0, 0, 0.33)',
      'text-halo-width': 0.5,
    },
  },
]
