// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_street_default: MapboxStyleLayer[] = [
  {
    id: 'street parking lines',
    type: 'line',
    filter: ['has', 'capacity'],
    paint: {
      'line-color': 'rgb(22, 163, 74)',
      'line-opacity': ['case', ['match', ['get', 'staggered'], ['yes'], true, false], 0.5, 1],
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 16],
    },
  },
]
