// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_street_completeness: MapboxStyleLayer[] = [
  {
    id: 'complete_no',
    type: 'line',
    filter: ['match', ['get', 'parking'], ['no', 'separate'], true, false],
    paint: {
      'line-color': 'hsl(273, 78%, 37%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
    },
  },
  {
    id: 'complete_data_missing',
    type: 'line',
    filter: ['match', ['get', 'parking'], ['missing'], true, false],
    paint: {
      'line-color': 'rgb(187, 17, 133)',
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
    },
  },
  {
    id: 'complete_too_small',
    type: 'line',
    filter: ['match', ['get', 'reason'], ['capacity_below_zero'], true, false],
    paint: {
      'line-color': 'rgb(99, 53, 50)',
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
    },
  },
]
