// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_street_areas_shadow: MapboxStyleLayer[] = [
  {
    id: 'area-color',
    type: 'fill',
    paint: {
      'fill-color': 'rgb(97, 143, 168)',
      'fill-opacity': 0.15,
    },
  },
  {
    id: 'area-outline',
    type: 'line',
    paint: {
      'line-color': 'rgb(107, 114, 118)',
      'line-dasharray': [1, 1],
      'line-opacity': 0.9,
    },
  },
]
