// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_tilda_parking_condition: MapboxStyleLayer[] = [
  {
    id: 'street parking line condition',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': ['match', ['get', 'operator_type'], ['private'], 0.33, 1],
      'line-color': [
        'case',
        [
          'any',
          ['in', 'residents', ['get', 'condition_category']],
          ['in', 'paid', ['get', 'condition_category']],
        ],
        'hsl(200, 94%, 50%)',
        ['in', 'time_limited', ['get', 'condition_category']],
        'hsl(60, 94%, 50%)',
        ['in', 'loading', ['get', 'condition_category']],
        'hsl(30, 94%, 50%)',
        ['in', 'charging', ['get', 'condition_category']],
        'hsl(120, 94%, 50%)',
        ['in', 'car_sharing', ['get', 'condition_category']],
        'hsl(280, 94%, 63%)',
        [
          'any',
          ['in', 'disabled', ['get', 'condition_category']],
          ['in', 'disabled_private', ['get', 'condition_category']],
        ],
        'hsl(0, 94%, 50%)',
        ['in', 'taxi', ['get', 'condition_category']],
        'hsl(300, 94%, 50%)',
        ['in', 'vehicle_restriction', ['get', 'condition_category']],
        'hsl(180, 94%, 50%)',
        ['in', 'access_restriction', ['get', 'condition_category']],
        'hsl(240, 94%, 50%)',
        ['in', 'no_parking', ['get', 'condition_category']],
        'hsl(15, 94%, 50%)',
        ['in', 'no_stopping', ['get', 'condition_category']],
        'hsl(0, 94%, 35%)',
        [
          'any',
          ['in', 'free', ['get', 'condition_category']],
          ['in', 'assumed_free', ['get', 'condition_category']],
        ],
        'hsl(142, 94%, 40%)',
        ['has', 'condition_category'],
        'hsl(320, 94%, 70%)',
        'hsl(320, 94%, 70%)',
      ],
    },
    filter: [
      'all',
      ['has', 'capacity'],
      ['match', ['get', 'operator_type'], ['private'], false, true],
    ],
  },
]
