// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_tilda_parkings_missing: MapboxStyleLayer[] = [
  {
    id: 'not expected',
    type: 'line',
    filter: ['match', ['get', 'parking'], ['missing'], true, false],
    paint: {
      'line-color': 'rgb(187, 17, 133)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
    },
  },
]
