// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_tilda_parkings_completeness: MapboxStyleLayer[] = [
  {
    id: 'missing-or-not-expected',
    type: 'line',
    paint: {
      'line-color': [
        'match',
        ['get', 'parking'],
        ['missing'],
        'rgb(187, 17, 133)',
        ['not_expected'],
        'rgb(116, 88, 107)',
        'rgb(0, 0, 0)',
      ],
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
    },
    filter: [
      'all',
      ['match', ['get', 'parking'], ['missing', 'not_expected'], true, false],
      ['match', ['get', 'reason'], ['capacity_below_zero'], false, true],
    ],
  },
  {
    id: 'too-small',
    type: 'line',
    paint: {
      'line-color': 'rgb(182, 164, 164)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
    },
    filter: ['match', ['get', 'reason'], ['capacity_below_zero'], true, false],
  },
]
