// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_tilda_parkings_no: MapboxStyleLayer[] = [
  {
    id: 'no',
    type: 'line',
    paint: {
      'line-color': 'rgb(0, 0, 0)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
    },
    filter: [
      'all',
      ['match', ['get', 'reason'], ['capacity_below_zero'], false, true],
      ['match', ['get', 'parking'], ['no', 'no_parking', 'no_stopping'], true, false],
    ],
  },
]
