// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_tilda_parkings_position: MapboxStyleLayer[] = [
  {
    id: 'street parking line position',
    type: 'line',
    paint: {
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': ['match', ['get', 'operator_type'], ['private'], 0.33, 1],
      'line-color': [
        'case',
        ['match', ['get', 'parking'], ['half_on_kerb'], true, false],
        'hsl(142, 94%, 40%)',
        ['match', ['get', 'parking'], ['on_kerb'], true, false],
        'hsl(164, 92%, 42%)',
        ['match', ['get', 'parking'], ['shoulder'], true, false],
        'hsl(200, 94%, 50%)',
        ['match', ['get', 'parking'], ['lane'], true, false],
        'hsl(344, 93%, 35%)',
        ['match', ['get', 'parking'], ['street_side'], true, false],
        'hsl(30, 94%, 50%)',
        ['match', ['get', 'parking'], ['separate'], true, false],
        'hsl(280, 94%, 63%)',
        ['has', 'parking'],
        'hsl(320, 94%, 70%)',
        'rgb(0, 0, 0)',
      ],
    },
    filter: [
      'all',
      ['has', 'capacity'],
      ['match', ['get', 'operator_type'], ['private'], false, true],
    ],
  },
]
