// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_tilda_parkinglines_completeness: MapboxStyleLayer[] = [
  {
    id: 'capacity_status-segment_too_small',
    type: 'line',
    filter: [
      'all',
      ['match', ['get', 'parking'], ['no'], true, false],
      ['match', ['get', 'capacity'], ['0'], true, false],
    ],
    paint: {
      'line-color': 'rgb(99, 53, 50)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-dasharray': [0.5, 0.5],
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
    },
  },
  {
    id: 'capacity_status-no_parking',
    type: 'line',
    filter: ['match', ['get', 'parking'], ['no'], true, false],
    paint: {
      'line-color': 'hsl(273, 78%, 37%)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
    },
  },
  {
    id: 'capacity_status-data_missing',
    type: 'line',
    filter: ['match', ['get', 'parking'], ['missing'], true, false],
    paint: {
      'line-color': 'rgb(187, 17, 133)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 10],
      'line-opacity': [
        'match',
        ['get', 'highway'],
        ['secondary', 'construction', 'pedestrian'],
        0.25,
        1,
      ],
    },
  },
]
