// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_tilda_parkings: MapboxStyleLayer[] = [
  {
    id: 'street parking lines',
    type: 'line',
    filter: [
      'all',
      ['has', 'capacity'],
      ['match', ['get', 'operator_type'], ['private'], false, true],
    ],
    paint: {
      'line-color': 'rgb(22, 163, 74)',
      'line-width': ['interpolate', ['linear'], ['zoom'], 16, 2, 20, 16],
      'line-opacity': ['match', ['get', 'operator_type'], ['private'], 0.33, 1],
    },
  },
]
