require('init')
local SANITIZE_TAGS = require('sanitize_tags')

describe('sanitize_tags', function()
  describe('access', function()
    it('allows destination', function()
      assert.are.equal(SANITIZE_TAGS.access('destination'), 'destination')
    end)
  end)

  describe('informal', function()
    it('drops unknown', function()
      assert.is_nil(SANITIZE_TAGS.informal('unknown'))
    end)
    it('keeps yes', function()
      assert.are.equal(SANITIZE_TAGS.informal('yes'), 'yes')
    end)
  end)
end)
