// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import type { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_street_areas_shadow: MapboxStyleLayer[] = [
  {
    id: 'area-color',
    type: 'fill',
    paint: {
      'fill-color': 'rgba(97, 143, 168, 0.5)',
      'fill-opacity': 0.15,
    },
  },
  {
    id: 'area-outline',
    type: 'line',
    paint: {
      'line-color': 'rgba(107, 114, 118, 0.5)',
      'line-dasharray': [1, 1],
      'line-opacity': 0.9,
    },
  },
]
