// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import type { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_park_street_kind: MapboxStyleLayer[] = [
  {
    id: 'street_kind',
    type: 'line',
    filter: ['has', 'capacity'],
    paint: {
      'line-color': [
        'match',
        ['get', 'parking'],
        ['street_side'],
        'rgb(179, 179, 179)',
        ['shoulder'],
        'rgb(204, 204, 204)',
        ['half_on_kerb'],
        'rgb(77, 77, 77)',
        ['on_kerb'],
        'rgb(26, 26, 26)',
        'rgb(128, 128, 128)',
      ],
      'line-opacity': ['case', ['match', ['get', 'staggered'], ['yes'], true, false], 0.5, 1],
      'line-width': ['interpolate', ['linear'], ['zoom'], 15, 2, 20, 16],
    },
  },
]
