import { existsSync, writeFileSync } from 'node:fs'
import { resolveRunningAttachStack } from './devStackDiscovery'
import {
  allocatePortPair,
  composeContainerPrefixFromStackId,
  publishedHostPorts,
  stackIdFromRepoRoot,
} from './devStackPorts'
import { envPath, repoRootFromApp } from './ensureEnv'
import {
  currentGitBranch,
  envLocalPath,
  isLinkedWorktree,
  syncEnvLocalForBranch,
  usesIsolatedDevStack,
} from './envLocalBranch'
import { logErr, logOk, logWarn } from './predevLog'

const label = 'ensure_dev_stack'

export { envLocalPath } from './envLocalBranch'
export { listRunningDevStacks } from './devStackDiscovery'

function formatEnvLocal(values: Record<string, string>) {
  const lines = [
    '# Auto-generated by predev — worktree-specific ports and Docker names.',
    '# Do not commit. Regenerated when missing.',
    `# DEV_STACK_BRANCH=${values.DEV_STACK_BRANCH}`,
    '',
    `DATABASE_PORT=${values.DATABASE_PORT}`,
    `TILES_PORT=${values.TILES_PORT}`,
    `DEV_STACK_ID=${values.DEV_STACK_ID}`,
  ]
  if (values.DEV_ATTACH_STACK) {
    lines.push(`DEV_ATTACH_STACK=${values.DEV_ATTACH_STACK}`)
  }
  return `${lines.join('\n')}\n`
}

export async function ensureDevStack() {
  const repoRoot = repoRootFromApp()
  const localPath = envLocalPath(repoRoot)

  if (!existsSync(envPath(repoRoot))) {
    logErr(label, '.env missing — run ensureEnv first')
    process.exit(1)
  }

  const branch = await currentGitBranch(repoRoot)
  const sync = await syncEnvLocalForBranch(repoRoot)
  if (sync.action === 'removed_on_default_branch') {
    logWarn(label, 'Removed .env.local on develop/main')
  } else if (sync.action === 'stale_removed') {
    logWarn(label, `Removed stale .env.local for branch ${sync.branch}`)
  } else if (sync.action === 'env_example_restored') {
    logWarn(label, 'Restored .env.example on develop/main')
  }

  if (!usesIsolatedDevStack(branch)) {
    logOk(label)
    return
  }

  if (existsSync(localPath)) {
    logOk(label)
    return
  }

  const attachFromEnv = process.env.DEV_ATTACH_STACK?.trim() || undefined
  const stackId = stackIdFromRepoRoot(repoRoot)
  let databasePort: number
  let tilesPort: number
  let attachStack: string | undefined

  if (!attachFromEnv && !(await isLinkedWorktree(repoRoot))) {
    logWarn(
      label,
      `Feature branches should use a worktree, not the main checkout. Run: bun run setup-worktree -- ${branch} — see docs/docker-local-development.md`,
    )
  }

  if (attachFromEnv) {
    const attached = await resolveRunningAttachStack(attachFromEnv)
    databasePort = attached.databasePort
    tilesPort = attached.tilesPort
    attachStack = attachFromEnv
    logWarn(label, `Attaching to stack "${attachFromEnv}" (db ${databasePort}, tiles ${tilesPort})`)
  } else {
    const allocated = await allocatePortPair()
    databasePort = allocated.databasePort
    tilesPort = allocated.tilesPort
    logWarn(
      label,
      `Allocated isolated stack: db ${databasePort}, tiles ${tilesPort}, stack ${stackId}`,
    )
  }

  const content = formatEnvLocal({
    DEV_STACK_BRANCH: branch,
    DATABASE_PORT: String(databasePort),
    TILES_PORT: String(tilesPort),
    DEV_STACK_ID: stackId,
    ...(attachStack ? { DEV_ATTACH_STACK: attachStack } : {}),
  })

  writeFileSync(localPath, content)
  logOk(`${label} (wrote ${localPath})`)
}

export function getStackPortsFromEnv() {
  const dbPort = Number(process.env.DATABASE_PORT) || 5432
  const tilesPort = Number(process.env.TILES_PORT) || 3000
  return { dbPort, tilesPort }
}

export function isAttachMode() {
  return Boolean(process.env.DEV_ATTACH_STACK?.trim())
}

/** This worktree's stack id — used for `docker compose -p`. */
export function devStackIdFromEnv() {
  const stackId = process.env.DEV_STACK_ID?.trim()
  if (stackId) return stackId
  const legacyPrefix = process.env.COMPOSE_DEV_CONTAINER_PREFIX?.trim()
  if (legacyPrefix) return legacyPrefix.replace(/_$/, '')
  return undefined
}

/** Stack whose containers to use (`DEV_ATTACH_STACK` when attaching, else own stack). */
export function dockerStackIdFromEnv() {
  const attach = process.env.DEV_ATTACH_STACK?.trim()
  if (attach === 'default') return undefined
  if (attach) return attach
  return devStackIdFromEnv()
}

/** Runtime-only prefix for `docker-compose.override.yml` container names. */
export function composeContainerPrefixFromEnv() {
  return composeContainerPrefixFromStackId(dockerStackIdFromEnv() ?? '')
}

export async function stackPortsArePublished() {
  const { dbPort, tilesPort } = getStackPortsFromEnv()
  const published = await publishedHostPorts()
  return published.has(dbPort) && published.has(tilesPort)
}

if (import.meta.main) {
  await ensureDevStack()
}
