import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { allocatePortPair, containerPrefixFromRepoRoot, publishedHostPorts } from './devStackPorts'
import { envPath, repoRootFromApp } from './ensureEnv'
import { logErr, logOk, logWarn } from './predevLog'

const label = 'ensure_dev_stack'

type DevStackRegistry = Record<
  string,
  {
    repoRoot: string
    databasePort: number
    tilesPort: number
    containerPrefix: string
    updatedAt: string
  }
>

function registryPath() {
  return join(homedir(), '.cache', 'tilda-geo', 'dev-stacks.json')
}

function envLocalPath(repoRoot = repoRootFromApp()) {
  return join(repoRoot, '.env.local')
}

export function readRegistry(): DevStackRegistry {
  const path = registryPath()
  if (!existsSync(path)) return {}
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as DevStackRegistry
  } catch {
    return {}
  }
}

function writeRegistry(registry: DevStackRegistry) {
  const path = registryPath()
  mkdirSync(join(path, '..'), { recursive: true })
  writeFileSync(path, `${JSON.stringify(registry, null, 2)}\n`)
}

function formatEnvLocal(values: Record<string, string>) {
  const lines = [
    '# Auto-generated by predev — worktree-specific ports and Docker names.',
    '# Do not commit. Regenerated when missing.',
    '',
    `DATABASE_PORT=${values.DATABASE_PORT}`,
    `TILES_PORT=${values.TILES_PORT}`,
    `COMPOSE_DEV_CONTAINER_PREFIX=${values.COMPOSE_DEV_CONTAINER_PREFIX}`,
    `DEV_STACK_ID=${values.DEV_STACK_ID}`,
  ]
  if (values.DEV_ATTACH_STACK) {
    lines.push(`DEV_ATTACH_STACK=${values.DEV_ATTACH_STACK}`)
  }
  return `${lines.join('\n')}\n`
}

function registerStack(
  stackId: string,
  repoRoot: string,
  databasePort: number,
  tilesPort: number,
  containerPrefix: string,
) {
  const registry = readRegistry()
  registry[stackId] = {
    repoRoot,
    databasePort,
    tilesPort,
    containerPrefix,
    updatedAt: new Date().toISOString(),
  }
  writeRegistry(registry)
}

function resolveAttachStack(attachName: string) {
  const registry = readRegistry()
  const entry = registry[attachName]
  if (!entry) {
    throw new Error(
      `DEV_ATTACH_STACK=${attachName} not found in ${registryPath()}. Start that stack once without attach.`,
    )
  }
  return entry
}

export async function ensureDevStack(options?: { attachStack?: string }) {
  const repoRoot = repoRootFromApp()
  const localPath = envLocalPath(repoRoot)

  if (!existsSync(envPath(repoRoot))) {
    logErr(label, '.env missing — run ensureEnv first')
    process.exit(1)
  }

  if (existsSync(localPath)) {
    logOk(label)
    return
  }

  const attachFromEnv =
    options?.attachStack?.trim() || process.env.DEV_ATTACH_STACK?.trim() || undefined
  const stackId = containerPrefixFromRepoRoot(repoRoot).replace(/_$/, '')
  let databasePort: number
  let tilesPort: number
  let containerPrefix: string
  let attachStack: string | undefined

  if (attachFromEnv) {
    const attached = resolveAttachStack(attachFromEnv)
    databasePort = attached.databasePort
    tilesPort = attached.tilesPort
    containerPrefix = attached.containerPrefix
    attachStack = attachFromEnv
    logWarn(label, `Attaching to stack "${attachFromEnv}" (db ${databasePort}, tiles ${tilesPort})`)
  } else {
    const allocated = await allocatePortPair()
    databasePort = allocated.databasePort
    tilesPort = allocated.tilesPort
    containerPrefix = containerPrefixFromRepoRoot(repoRoot)
    logWarn(
      label,
      `Allocated isolated stack: db ${databasePort}, tiles ${tilesPort}, prefix ${containerPrefix}`,
    )
  }

  const content = formatEnvLocal({
    DATABASE_PORT: String(databasePort),
    TILES_PORT: String(tilesPort),
    COMPOSE_DEV_CONTAINER_PREFIX: containerPrefix,
    DEV_STACK_ID: stackId,
    ...(attachStack ? { DEV_ATTACH_STACK: attachStack } : {}),
  })

  writeFileSync(localPath, content)
  registerStack(stackId, repoRoot, databasePort, tilesPort, containerPrefix)
  logOk(`${label} (wrote ${localPath})`)
}

export function getStackPortsFromEnv() {
  const dbPort = Number(process.env.DATABASE_PORT) || 5432
  const tilesPort = Number(process.env.TILES_PORT) || 3000
  return { dbPort, tilesPort }
}

export function isAttachMode() {
  return Boolean(process.env.DEV_ATTACH_STACK?.trim())
}

export async function stackPortsArePublished() {
  const { dbPort, tilesPort } = getStackPortsFromEnv()
  const published = await publishedHostPorts()
  return published.has(dbPort) && published.has(tilesPort)
}

if (import.meta.main) {
  await ensureDevStack()
}
