// We use bun.sh to run this file

import path from 'node:path'
import { styleText } from 'node:util'
import {
  ensureDetailsForContinents,
  getLayers,
  getManifest,
  hydrateLayers,
  type EliLayer,
} from '@osm-editor-kit/maplibre-editor-layer-index'
import { getRasterSourceSpec } from '@osm-editor-kit/maplibre-editor-layer-index/maplibre'
import { $ } from 'bun'
import type { MapDataBackgroundSource } from '@/components/regionen/pageRegionSlug/mapData/types'
import legacyIds from './legacyIds.json'
import legacyLayers from './legacyLayers.json'
import { log, warn } from './util'

console.log(styleText(['inverse', 'bold'], 'START'), __filename)

const appDir = path.resolve(import.meta.dir, '../..')
const outputFile = path.join(
  import.meta.dir,
  '../../src/components/regionen/pageRegionSlug/mapData/mapDataSources/sourcesBackgroundRasterELI.const.ts',
)

/**
 * Ids are stored in the region configs, so they must not change. Layers that this file had
 * before it was built from the package keep the id they had (`legacyIds.json`, matched once
 * by tile URL); new layers are named after their ELI id.
 */
const tildaId = (eliId: string) =>
  (legacyIds as Record<string, string>)[eliId] ??
  `ELI_${eliId
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')}`

const roundBbox = (bbox: EliLayer['bbox']) =>
  bbox.map((value) => Math.round(value * 1e4) / 1e4) as EliLayer['bbox']

function toBackgroundSource(layer: EliLayer) {
  // WMS images at twice the tile size, so they stay sharp on high-density screens.
  const spec = getRasterSourceSpec(layer, { pixelRatio: 2 })
  const [tilesUrl] = spec.tiles
  if (!tilesUrl) {
    warn(`No tile URL for: ${layer.name}`)
    return null
  }
  if (!layer.attributionText) warn(`Missing attribution for: ${layer.name}, using empty string`)

  const result: MapDataBackgroundSource<string> = {
    id: tildaId(layer.id),
    name: layer.name,
    tilesUrl,
    // The plain text, as before; the HTML variant of the package wraps it in a link.
    attributionHtml: layer.attributionText ?? '',
    tileSize: spec.tileSize,
    bbox: roundBbox(layer.bbox),
  }
  if (spec.minzoom !== undefined) result.minzoom = spec.minzoom
  if (spec.maxzoom !== undefined) result.maxzoom = spec.maxzoom
  if (spec.scheme === 'tms') result.scheme = 'tms'
  if (layer.category) result.category = layer.category
  if (layer.best) result.best = true
  if (layer.endDate) result.endDate = layer.endDate
  return result
}

async function main() {
  const manifest = getManifest()
  log(`Editor Layer Index as of ${manifest.generatedAt} (${manifest.sourceCommit})`)

  await ensureDetailsForContinents(['europe', 'world'])
  // Layers whose coverage touches Germany, including those of neighbours that reach across
  // the border. Worldwide layers are not part of this list; TILDA keeps its own.
  const layers = hydrateLayers(getLayers().filter((layer) => layer.countryCodes.includes('DE')))
  log(`Found ${layers.length} layers for Germany`)

  const converted = layers.flatMap((layer) => {
    if (layer.requiresKeys.length > 0) {
      warn(`Skipping layer that needs an API key: ${layer.name}`)
      return []
    }
    return toBackgroundSource(layer) ?? []
  })

  // Layers that left the index but may still be selected in a region config.
  const known = new Set(converted.map((layer) => layer.id))
  const retired = (legacyLayers as MapDataBackgroundSource<string>[]).filter(
    (layer) => !known.has(layer.id),
  )
  if (retired.length > 0) log(`Keeping ${retired.length} layers that left the index`)

  const sources = [...converted, ...retired].sort((a, b) => a.id.localeCompare(b.id))
  const typeIds = sources.map((layer) => `  | '${layer.id}'`).join('\n')

  const typeScriptContent = `// DO NOT EDIT MANUALLY
// This file was automatically generated by \`scripts/ELILayers/process.ts\`

import type { MapDataBackgroundSource } from '@/components/regionen/pageRegionSlug/mapData/types'

export type SourcesRasterIdsELI =
${typeIds}

export const sourcesBackgroundsRasterELI: MapDataBackgroundSource<SourcesRasterIdsELI>[] = ${JSON.stringify(
    sources,
    null,
    2,
  )}
`

  await Bun.write(outputFile, typeScriptContent)
  log(`Generated ${outputFile} with ${sources.length} layers`)

  log('bun run format')
  await $`bun run format`.cwd(appDir)
}

main().catch((error) => {
  console.error(styleText('red', 'Error:'), error)
  process.exit(1)
})
