#!/usr/bin/env nub

// This script generates the files `./_{checksum}.ts` and `./index.ts`
// don't run it directly but use `nub run regions:configs` which runs oxfmt after code generation

import fs from 'node:fs'
import path from 'node:path'
import { getSimplifiedConfigs } from './lib'

const configsFolder = path.join(import.meta.dirname, 'configs')

const resultIntro = `
// DO NOT EDIT MANUALLY
// This file was automatically generated by \`${path.basename(import.meta.filename)}\`
`

getSimplifiedConfigs().forEach(({ config, regionSlugs }, checksum) => {
  const moduleName = `_${checksum}`
  const modulePath = path.join(configsFolder, `${moduleName}.ts`)
  const result = `${resultIntro}
import type { MapDataCategoryParam } from '../../type'

// For regions ${regionSlugs.join(', ')}
export const ${moduleName}: MapDataCategoryParam[] = ${JSON.stringify(config)}
    `
  fs.writeFileSync(modulePath, result)
  console.log(`Updated ${modulePath}...`)
})

const configModules = fs
  .readdirSync(configsFolder)
  .filter((filename) => !filename.startsWith('index'))
  .map((filename) => filename.split('.')[0])
  .sort()

const importCode = configModules
  .map((filename) => {
    return `import { ${filename} } from './${filename}'`
  })
  .join('\n')

const result = `${resultIntro}

${importCode}

export const configs = {
  ${configModules.map((filename) => {
    return `"${filename?.slice(1)}": ${filename}`
  })}
}
`
const modulePath = path.join(configsFolder, 'index.ts')
fs.writeFileSync(modulePath, result)
console.log(`Updated ${modulePath}...`)
