// DO NOT EDIT MANUALLY
// This file was automatically generated by `saveConfigs.ts`

import { MapDataCategoryParam } from '../../type'

// For regions testing
export const _18xypp8: MapDataCategoryParam[] = [
  {
    id: 'poi',
    active: false,
    subcategories: [
      {
        id: 'poi',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'education', active: false },
        ],
      },
      {
        id: 'poiPlaces',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'circle', active: false },
        ],
      },
      {
        id: 'poiBoundaries',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
          { id: 'category_district_label', active: false },
          { id: 'category_municipality', active: false },
          { id: 'category_municipality_label', active: false },
        ],
      },
      { id: 'poiPlusBarriers', styles: [{ id: 'default', active: false }] },
      { id: 'poiPlusLanduse', styles: [{ id: 'default', active: false }] },
      { id: 'poiPlusPublicTransport', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'boundaries',
    active: false,
    subcategories: [
      {
        id: 'poiPlaces',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
          { id: 'circle', active: false },
        ],
      },
      {
        id: 'poiBoundaries',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'category_district_label', active: false },
          { id: 'category_municipality', active: false },
          { id: 'category_municipality_label', active: false },
        ],
      },
      { id: 'poiPlusBarriers', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'roads',
    active: false,
    subcategories: [
      {
        id: 'roads',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'sidestreets', active: false },
          { id: 'mainstreets', active: false },
          { id: 'classified', active: false },
        ],
      },
      {
        id: 'maxspeed',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
          { id: 'below30', active: false },
          { id: 'above40', active: false },
        ],
      },
      { id: 'roads_plus_oneway', styles: [{ id: 'default', active: false }] },
      { id: 'roads_plus_footways', styles: [{ id: 'default', active: false }] },
      { id: 'roads_plus_label', styles: [{ id: 'default', active: true }] },
    ],
  },
  {
    id: 'bikelanes',
    active: false,
    subcategories: [
      {
        id: 'bikelanes',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'details', active: false },
          { id: 'width', active: false },
        ],
      },
      { id: 'bikelanes_plus_presence', styles: [{ id: 'default', active: false }] },
      { id: 'bikelanes_plus_width', styles: [{ id: 'default', active: false }] },
      { id: 'bikelanes_plus_surface_smoothness', styles: [{ id: 'default', active: false }] },
      { id: 'bikelanes_plus_signs', styles: [{ id: 'default', active: false }] },
      { id: 'bikelanes_plus_routes', styles: [{ id: 'default', active: false }] },
      { id: 'bikelanes_plus_bikesuitability', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'bikelanes-minimal',
    active: false,
    subcategories: [
      {
        id: 'bikelanes',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'details', active: false },
          { id: 'width', active: false },
        ],
      },
    ],
  },
  {
    id: 'lit',
    active: false,
    subcategories: [
      {
        id: 'lit',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'lit', active: false },
        ],
      },
      { id: 'lit-completeness', styles: [{ id: 'completeness', active: false }] },
    ],
  },
  {
    id: 'surface',
    active: false,
    subcategories: [
      {
        id: 'surfaceRoads',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'bad', active: false },
        ],
      },
      {
        id: 'surfaceBikelanes',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
          { id: 'bad', active: false },
        ],
      },
    ],
  },
  {
    id: 'parkingLars',
    active: false,
    subcategories: [
      {
        id: 'parkingLars',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'presence', active: false },
          { id: 'missing', active: false },
          { id: 'surface', active: false },
        ],
      },
      {
        id: 'parkingPoints',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingAreas',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'street_side', active: false },
        ],
      },
      {
        id: 'parkingDebug',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingStats',
        styles: [
          { id: 'hidden', active: true },
          { id: 'stats-admin-level-4', active: false },
          { id: 'default', active: false },
          { id: 'stats-admin-level-10', active: false },
          { id: 'length-admin-level-4', active: false },
          { id: 'length-admin-level-9', active: false },
          { id: 'length-admin-level-10', active: false },
        ],
      },
      {
        id: 'parkingBoundaries',
        styles: [
          { id: 'hidden', active: true },
          { id: 'boundaries-admin-level-4', active: false },
          { id: 'boundaries-admin-level-9', active: false },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'signs',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
    ],
  },
  {
    id: 'bicycleParking',
    active: false,
    subcategories: [
      {
        id: 'bicycleParking',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
        ],
      },
    ],
  },
  {
    id: 'statistics',
    active: false,
    subcategories: [
      {
        id: 'bikelanesStatistics',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'category_municipality', active: false },
        ],
      },
      {
        id: 'poiBoundaries',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'category_district_label', active: false },
          { id: 'category_municipality', active: false },
          { id: 'category_municipality_label', active: false },
        ],
      },
    ],
  },
  {
    id: 'mapillary',
    active: false,
    subcategories: [
      {
        id: 'mapillaryCoverage',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'all', active: false },
          { id: 'age', active: false },
          { id: 'pano', active: false },
        ],
      },
    ],
  },
  {
    id: 'accidents',
    active: false,
    subcategories: [
      {
        id: 'accidents',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
        ],
      },
    ],
  },
  {
    id: 'radinfra_bikelanes',
    active: false,
    subcategories: [
      {
        id: 'bikelanes',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'details', active: false },
        ],
      },
      { id: 'bikelanes_plus_routes', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'radinfra_surface',
    active: false,
    subcategories: [
      { id: 'bikelanes', styles: [{ id: 'default', active: true }] },
      { id: 'bikelanes_plus_surface_smoothness', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'radinfra_width',
    active: false,
    subcategories: [
      { id: 'bikelanes', styles: [{ id: 'default', active: true }] },
      { id: 'bikelanes_plus_width', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'radinfra_oneway',
    active: false,
    subcategories: [{ id: 'bikelanes', styles: [{ id: 'default', active: true }] }],
  },
  {
    id: 'radinfra_trafficSigns',
    active: false,
    subcategories: [{ id: 'bikelanes', styles: [{ id: 'default', active: true }] }],
  },
  {
    id: 'radinfra_currentness',
    active: false,
    subcategories: [{ id: 'bikelanes', styles: [{ id: 'default', active: true }] }],
  },
  {
    id: 'radinfra_campagins',
    active: false,
    subcategories: [
      {
        id: 'campaigns',
        styles: [
          { id: 'default', active: true },
          { id: 'adjoining_or_isolated', active: false },
          { id: 'advisory_or_exclusive', active: false },
          { id: 'advisory_or_exclusive__mapillary', active: false },
          { id: 'currentness_too_old', active: false },
          { id: 'currentness_too_old__mapillary', active: false },
          { id: 'deprecated_cycleway_shared', active: false },
          { id: 'malformed_traffic_sign', active: false },
          { id: 'malformed_traffic_sign__mapillary', active: false },
          { id: 'missing_access_tag_240', active: false },
          { id: 'missing_access_tag_bicycle_road', active: false },
          { id: 'missing_oneway', active: false },
          { id: 'missing_oneway__mapillary', active: false },
          { id: 'missing_segregated', active: false },
          { id: 'missing_segregated__mapillary', active: false },
          { id: 'missing_surface', active: false },
          { id: 'missing_surface__mapillary', active: false },
          { id: 'missing_traffic_sign', active: false },
          { id: 'missing_traffic_sign__mapillary', active: false },
          { id: 'missing_traffic_sign_244', active: false },
          { id: 'missing_traffic_sign_244__mapillary', active: false },
          { id: 'missing_traffic_sign_vehicle_destination', active: false },
          { id: 'missing_traffic_sign_vehicle_destination__mapillary', active: false },
          { id: 'missing_width', active: false },
          { id: 'missing_width_surface_sett__mapillary', active: false },
          { id: 'mixed_cycleway_both', active: false },
          { id: 'mixed_cycleway_both__mapillary', active: false },
          { id: 'needs_clarification', active: false },
          { id: 'needs_clarification__mapillary', active: false },
          { id: 'needs_clarification_track', active: false },
          { id: 'needs_clarification_track__mapillary', active: false },
          { id: 'unexpected_bicycle_access_on_footway', active: false },
          { id: 'unexpected_bicycle_access_on_footway__mapillary', active: false },
        ],
      },
    ],
  },
  {
    id: 'radinfra_statistics',
    active: false,
    subcategories: [
      {
        id: 'stats',
        styles: [
          { id: 'default', active: true },
          { id: 'level6', active: false },
        ],
      },
    ],
  },
  {
    id: 'radinfra_mapillary',
    active: false,
    subcategories: [
      {
        id: 'mapillaryCoverage',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'all', active: false },
          { id: 'age', active: false },
          { id: 'pano', active: false },
        ],
      },
      { id: 'mapillaryPlus', styles: [{ id: 'default', active: true }] },
    ],
  },
  {
    id: 'parkingTilda',
    active: false,
    subcategories: [
      {
        id: 'parkingTilda',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
        ],
      },
      {
        id: 'parkingTildaCutouts',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingTildaQuantized',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingTildaSeparate',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
        ],
      },
      {
        id: 'parkingTildaNo',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
    ],
  },
]
