// DO NOT EDIT MANUALLY
// This file was automatically generated by `saveConfigs.ts`

import { MapDataCategoryParam } from '../../type'

// For regions parkraum-berlin
export const _1p5jpsu: MapDataCategoryParam[] = [
  {
    id: 'parkingTilda',
    active: false,
    subcategories: [
      {
        id: 'parkingTilda',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'surface', active: false },
          { id: 'kind', active: false },
        ],
      },
      {
        id: 'parkingTildaPrivate',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
          { id: 'surface', active: false },
          { id: 'kind', active: false },
        ],
      },
      {
        id: 'parkingTildaOffStreet',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'surface', active: false },
          { id: 'kind', active: false },
        ],
      },
      {
        id: 'parkingTildaOffStreetPrivate',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
          { id: 'surface', active: false },
          { id: 'kind', active: false },
        ],
      },
      { id: 'parkingTildaNo', styles: [{ id: 'default', active: false }] },
      { id: 'parkingTildaCutouts', styles: [{ id: 'default', active: false }] },
      { id: 'parkingTildaMissing', styles: [{ id: 'default', active: false }] },
      { id: 'parkingTildaQuantized', styles: [{ id: 'default', active: false }] },
      { id: 'parkingTildaQuantizedOffStreet', styles: [{ id: 'default', active: false }] },
    ],
  },
  {
    id: 'parkingLars',
    active: false,
    subcategories: [
      {
        id: 'parkingLars',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'presence', active: false },
          { id: 'missing', active: false },
          { id: 'surface', active: false },
        ],
      },
      { id: 'parkingPoints', styles: [{ id: 'default', active: false }] },
      {
        id: 'parkingAreas',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'street_side', active: false },
        ],
      },
      { id: 'parkingDebug', styles: [{ id: 'default', active: false }] },
      {
        id: 'parkingStats',
        styles: [
          { id: 'hidden', active: true },
          { id: 'stats-admin-level-4', active: false },
          { id: 'default', active: false },
          { id: 'stats-admin-level-10', active: false },
          { id: 'length-admin-level-4', active: false },
          { id: 'length-admin-level-9', active: false },
          { id: 'length-admin-level-10', active: false },
        ],
      },
      {
        id: 'parkingBoundaries',
        styles: [
          { id: 'hidden', active: true },
          { id: 'boundaries-admin-level-4', active: false },
          { id: 'boundaries-admin-level-9', active: false },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'signs',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
    ],
  },
  {
    id: 'mapillary',
    active: false,
    subcategories: [
      {
        id: 'mapillaryCoverage',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'all', active: false },
          { id: 'age', active: false },
          { id: 'pano', active: false },
        ],
      },
    ],
  },
]
