// DO NOT EDIT MANUALLY
// This file was automatically generated by `saveConfigs.ts`

import { MapDataCategoryParam } from '../../type'

// For regions parkraum-berlin
export const _1ye9tgd: MapDataCategoryParam[] = [
  {
    id: 'parkingTilda',
    active: false,
    subcategories: [
      {
        id: 'parkingTilda',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
        ],
      },
      {
        id: 'parkingTildaCutouts',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingTildaQuantized',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingTildaSeparate',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
        ],
      },
      {
        id: 'parkingTildaNo',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
    ],
  },
  {
    id: 'parkingLars',
    active: false,
    subcategories: [
      {
        id: 'parkingLars',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'presence', active: false },
          { id: 'missing', active: false },
          { id: 'surface', active: false },
        ],
      },
      {
        id: 'parkingPoints',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingAreas',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'street_side', active: false },
        ],
      },
      {
        id: 'parkingDebug',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'parkingStats',
        styles: [
          { id: 'hidden', active: true },
          { id: 'stats-admin-level-4', active: false },
          { id: 'default', active: false },
          { id: 'stats-admin-level-10', active: false },
          { id: 'length-admin-level-4', active: false },
          { id: 'length-admin-level-9', active: false },
          { id: 'length-admin-level-10', active: false },
        ],
      },
      {
        id: 'parkingBoundaries',
        styles: [
          { id: 'hidden', active: true },
          { id: 'boundaries-admin-level-4', active: false },
          { id: 'boundaries-admin-level-9', active: false },
          { id: 'default', active: false },
        ],
      },
      {
        id: 'signs',
        styles: [
          { id: 'hidden', active: true },
          { id: 'default', active: false },
        ],
      },
    ],
  },
  {
    id: 'mapillary',
    active: false,
    subcategories: [
      {
        id: 'mapillaryCoverage',
        styles: [
          { id: 'hidden', active: false },
          { id: 'default', active: true },
          { id: 'all', active: false },
          { id: 'age', active: false },
          { id: 'pano', active: false },
        ],
      },
    ],
  },
]
