name: Check PR

on: [pull_request]

jobs:
  run-app-ci:
    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: "app/.nvmrc"
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'

      - name: Install dependencies (with cache)
        run: npm ci

      - name: Check types
        run: npm run type-check

      - name: Check linting
        run: npm run lint

      - name: Run tests
        run: npm run test:run
  # Disabled due to error https://github.com/FixMyBerlin/tilda-geo/actions/runs/15585651343/job/43891057696?pr=209
  # > Run docker run test_img
  # > docker run test_img
  # > shell: /usr/bin/bash -e {0}
  # > 0 successes / 0 failures / 2 errors / 0 pending : 0.000013 seconds
  # > Error -> Cannot find file or directory: /processing/topics/
  # > Error -> No test files found matching Lua pattern: %.test%.lua$
  # > Error: Process completed with exit code 1.
  #
  # Probably because of 7662a493ff18695766e7ab8f5f9a30af0eac391a, bcba8dbdd4d212170b81cdc20598c3e3bd915b63
  # We don't need it on the CI that much, so its disabled for now.
  # We can always revert those changes later…
  #
  # run-processing-ci:
  #   name: Run Processing Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build Image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: ./processing.Dockerfile
  #         tags: test_img
  #         target: testing
  #         push: false
  #         load: true
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max

  #     - name: Run Tests
  #       run: |
  #         docker run test_img
