name: Force Full Deploy
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        required: true
        options:
          - staging
          - production
        description: 'Environment to deploy to (staging or production). This workflow bypasses all optimization checks and always performs a full deployment of both app and processing services.'

jobs:
  setup_env:
    uses: ./.github/workflows/setup-env.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TILES_URL: ${{ inputs.ENVIRONMENT == 'production' && 'tiles.tilda-geo.de' || 'staging-tiles.tilda-geo.de' }}
      CACHELESS_URL: ${{ inputs.ENVIRONMENT == 'production' && 'cacheless.tilda-geo.de' || 'staging-cacheless.tilda-geo.de' }}
      NEXT_PUBLIC_APP_ORIGIN: ${{ inputs.ENVIRONMENT == 'production' && 'https://tilda-geo.de' || 'https://staging.tilda-geo.de' }}
      NEXT_PUBLIC_APP_ENV: ${{ inputs.ENVIRONMENT }}
      APP_URL: ${{ inputs.ENVIRONMENT == 'production' && 'tilda-geo.de' || 'staging.tilda-geo.de' }}
    secrets: inherit
  restart_services:
    uses: ./.github/workflows/restart-services.yml
    needs: setup_env
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    secrets: inherit
  deploy_processing:
    uses: ./.github/workflows/deploy-processing.yml
    needs: restart_services
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TILES_URL: ${{ inputs.ENVIRONMENT == 'production' && 'tiles.tilda-geo.de' || 'staging-tiles.tilda-geo.de' }}
      CONFIG_CHANGED: ${{ needs.restart_services.outputs.CHANGES == 'true' }}
      PROCESSING_DIFFING_MODE: ${{ inputs.ENVIRONMENT == 'production' && 'off' || 'fixed' }}
      DIFF_CHECK_MODE: skip
    secrets: inherit
  deploy_app:
    uses: ./.github/workflows/deploy-app.yml
    needs: restart_services
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      NEXT_PUBLIC_APP_ORIGIN: ${{ inputs.ENVIRONMENT == 'production' && 'https://tilda-geo.de' || 'https://staging.tilda-geo.de' }}
      NEXT_PUBLIC_APP_ENV: ${{ inputs.ENVIRONMENT }}
      APP_URL: ${{ inputs.ENVIRONMENT == 'production' && 'tilda-geo.de' || 'staging.tilda-geo.de' }}
      CONFIG_CHANGED: ${{ needs.restart_services.outputs.CHANGES == 'true' }}
      DIFF_CHECK_MODE: skip
    secrets: inherit
