import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { $ } from 'bun'
import { POSTGRES_CLI_IMAGE } from '../db-pull/db-helpers'
import { SCHEMA } from './args'
import { getDockerDatabaseUrl } from './db'

/** pg_dump 17 adds psql \\restrict / \\unrestrict; strip so DBeaver etc. can run the file. */
function sanitizePgDumpForGuiClients(dump: string) {
  return dump
    .split('\n')
    .filter((line) => !/^\s*\\/.test(line))
    .join('\n')
    .trim()
}

export async function exportProductionSql({
  tableName,
  outputDir,
  sourceFile,
  rowCount,
  dryRun,
}: {
  tableName: string
  outputDir: string
  sourceFile: string
  rowCount: number
  dryRun: boolean
}) {
  mkdirSync(outputDir, { recursive: true })
  const outputPath = resolve(outputDir, `${tableName}.sql`)
  const qualified = `${SCHEMA}.${tableName}`
  const header = [
    '-- Generated by parking-cutouts-import',
    `-- Source: ${sourceFile}`,
    `-- Rows: ${rowCount}`,
    `-- Table: ${qualified}`,
    '',
    `TRUNCATE TABLE ${qualified} RESTART IDENTITY;`,
    '',
  ].join('\n')

  if (dryRun) {
    return {
      outputPath,
      command: `pg_dump --table=${qualified} --data-only --inserts → ${outputPath}`,
    }
  }

  const dockerUrl = getDockerDatabaseUrl()
  const dumpResult =
    await $`docker run --rm --add-host=host.docker.internal:host-gateway --entrypoint pg_dump ${POSTGRES_CLI_IMAGE} --no-owner --no-privileges --data-only --inserts --table=${qualified} ${dockerUrl}`
      .quiet()
      .nothrow()

  if (dumpResult.exitCode !== 0) {
    throw new Error(
      dumpResult.stderr.toString().trim() || `pg_dump failed (${dumpResult.exitCode})`,
    )
  }

  const body = sanitizePgDumpForGuiClients(dumpResult.stdout.toString())
  writeFileSync(outputPath, `${header}\n${body}\n`, 'utf8')
  return { outputPath }
}
